# Generated by Django 5.2.8 on 2026-01-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopMitra', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('ONLINE', 'Online Payment')], default='COD', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
